name: Build, test, and publish Docker Image

env:
  OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  schedule:
    # Weekly, at 07:00 on Monday UTC time
    - cron: "0 7 * * 1"
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-publish-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4

      - name: Set Up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dev Dependencies 📦
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements-dev.txt

      - name: Get commit sha, this will be used as a tag later on 🏷
        shell: bash
        run: |
          echo "sha12=$(echo ${GITHUB_SHA} | cut -c1-12)" >> $GITHUB_OUTPUT
        id: get_sha

      - name: Build image 🛠
        run: >
          docker build
          --rm --force-rm
          --tag ${{ env.OWNER }}/${{ env.IMAGE_NAME }}
          --tag ${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{steps.get_sha.outputs.sha12}}
          image/
        env:
          DOCKER_BUILDKIT: 1
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Run tests ✅
        run: python3 -m pytest tests
        env:
          TEST_IMAGE: "${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{steps.get_sha.outputs.sha12}}" # point this at the image we just built

      - name: Login to Docker Hub 🔐
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: rhprasad
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub 📤
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: docker push rhprasad/jupyter-scipy-mlflow:latest
